name: Ops Escalation Reason Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:        # Allow manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run Ops Escalation Reason Bot
        env:
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
          EMAIL: ${{ secrets.EMAIL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: python copy_ops_reason.py
