name: Shopify Order Lookup

on:
  repository_dispatch:
    types: [shopify_order_lookup]

jobs:
  lookup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run lookup script
        env:
          SHOPIFY_SHOP_DOMAIN: ${{ secrets.SHOPIFY_DOMAIN }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}
          ZENDESK_EMAIL: ${{ secrets.EMAIL }}
          ZENDESK_API_TOKEN: ${{ secrets.API_TOKEN }}
          ZENDESK_DOMAIN: ${{ secrets.SUBDOMAIN }}
          TICKET_ID: ${{ github.event.client_payload.ticket_id }}
          CUSTOMER_EMAIL: ${{ github.event.client_payload.customer_email }}
          CUSTOMER_PHONE: ${{ github.event.client_payload.customer_phone }}
        run: python shopify_to_zendesk.py
