name: Shopify → Zendesk Order Lookup

on:
  workflow_dispatch:
    inputs:
      ticket_id:
        description: "Zendesk Ticket ID"
        required: true
      customer_input:
        description: "Customer email or phone (966... without +)"
        required: true

jobs:
  fetch-orders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests
      - name: Run Shopify → Zendesk script
        env:
          SHOPIFY_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}
          SHOPIFY_DOMAIN: ${{ secrets.SHOPIFY_DOMAIN }}
          ZENDESK_EMAIL: ${{ secrets.EMAIL }}
          ZENDESK_TOKEN: ${{ secrets.API_TOKEN }}
          ZENDESK_SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
        run: python shopify_to_zendesk.py ${{ github.event.inputs.ticket_id }} "${{ github.event.inputs.customer_input }}"
