name: Zendesk Duplicate Merger

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:         # Allow manual trigger from GitHub Actions UI

jobs:
  merge-tickets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run merge script
        env:
          ZENDESK_EMAIL: ${{ secrets.EMAIL }}
          ZENDESK_TOKEN: ${{ secrets.TOKEN }}
          ZENDESK_SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
        run: |
          python merge_script.py
