name: Merge Zendesk Tickets

on:
  schedule:
    - cron: "*/10 * * * *" # every 10 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run merge bot
        env:
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
          EMAIL: ${{ secrets.EMAIL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: python merge_bot.py
