name: Zendesk → Shopify Auto Sync

on:
  repository_dispatch:
    types: [zendesk_ticket_note]

jobs:
  sync-note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests python-dotenv
      - name: Run Zendesk → Shopify sync
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
          SHOPIFY_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}
          SHOPIFY_DOMAIN: ${{ secrets.SHOPIFY_DOMAIN }}
        run: python script.py sync_note ${{ github.event.client_payload.ticket_id }}
