name: Zendesk → Shopify Sync

on:
  repository_dispatch:   # Triggered by Zendesk webhook
    types: [zendesk_ticket_note]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Zendesk → Shopify script
        env:
          ZENDESK_SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
          ZENDESK_EMAIL: ${{ secrets.EMAIL }}
          ZENDESK_API_TOKEN: ${{ secrets.API_TOKEN }}
          SHOPIFY_DOMAIN: ${{ secrets.SHOPIFY_DOMAIN }}
          SHOPIFY_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}
          TICKET_ID: ${{ github.event.client_payload.ticket_id }}
          ORDER_NUMBER: ${{ github.event.client_payload.order_number }}
        run: python script.py
