name: Zendesk → Shopify Sync

on:
  workflow_dispatch:
    inputs:
      ticket_id:
        description: 'Zendesk Ticket ID'
        required: true
      order_number:
        description: 'Order number from Zendesk'
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Zendesk → Shopify script
        env:
          ZENDESK_SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
          ZENDESK_EMAIL: ${{ secrets.EMAIL }}
          ZENDESK_API_TOKEN: ${{ secrets.API_TOKEN }}
          SHOPIFY_DOMAIN: ${{ secrets.SHOPIFY_DOMAIN }}
          SHOPIFY_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}
          TICKET_ID: ${{ github.event.inputs.ticket_id }}
          ORDER_NUMBER: ${{ github.event.inputs.order_number }}
        run: python script.py
