name: Zendesk → Shopify Sync

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'sync_note or retrieve_orders'
        required: true
      ticket_id:
        description: 'Zendesk ticket ID for sync_note'
        required: false
      identifier:
        description: 'Customer email or phone for retrieve_orders'
        required: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Install dependencies
        run: pip install -r requirements.txt python-dotenv

      - name: Update CA certificates
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates
          sudo update-ca-certificates

      - name: Run Zendesk → Shopify script
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
          SHOPIFY_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}
          SHOPIFY_DOMAIN: ${{ secrets.SHOPIFY_DOMAIN }}
        run: |
          python script.py ${{ github.event.inputs.action }} ${{ github.event.inputs.ticket_id || github.event.inputs.identifier }}
