name: Zendesk → Shopify Sync

'on':
  workflow_dispatch:
    inputs:
      action:
        description: 'sync_note'
        required: true
      ticket_id:
        description: 'Zendesk ticket ID for sync_note'
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir requests python-dotenv certifi

      - name: Configure Requests CA bundle
        run: |
          python - <<'PY' | tee -a "$GITHUB_ENV"
          import certifi
          print(f"SSL_CERT_FILE={certifi.where()}")
          print(f"REQUESTS_CA_BUNDLE={certifi.where()}")
          PY

      - name: Run Zendesk → Shopify script
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
          SHOPIFY_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}
          SHOPIFY_DOMAIN: ${{ secrets.SHOPIFY_DOMAIN }}
        run: |
          python script.py ${{ github.event.inputs.action }} ${{ github.event.inputs.ticket_id }}
